---
title: "git_00"
author: "teresa juan"
date: "Year 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

"Just the place for a Snark!" the Bellman cried,  
   As he landed his crew with care;  
Supporting each man on the top of the tide  
   By a finger entwined in his hair.  
"Just the place for a Snark! I have said it twice:


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

“You can’t because you don’t know how to speak.  
If you had any feelings, you that dug  
With your own hand—how could you?—his little grave;  
I saw you from that very window there,   
Making the gravel leap in air,  







## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright—  
And this was odd, because it was  
The middle of the night.  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

O my Luve is like a red, red rose  
   That’s newly sprung in June;  
O my Luve is like the melody  
   That’s sweetly played in tune. 
So fair art thou, my bonnie lass,  
   So deep in luve am I;  
And I will luve thee still, my dear,  
   Till a’ the seas gang dry.  
Till a’ the seas gang dry, my dear,  
   And the rocks melt wi’ the sun;  
I will love thee still, my dear,  
   While the sands o’ life shall run.  
And fare thee weel, my only luve!  
   And fare thee weel awhile!  
And I will come again, my luve,  
   Though it were ten thousand mile.  
